services:
  iris-backend:
    # CHANGE: Point this to your actual backend folder, NOT medmatch-ui
    build: ./backend
    container_name: medmatch-iris-server
    ports:
      - "52773:52773"
    volumes:
      - ./:/home/irisowner/dev
    ulimits:
      stack: 67108864
      memlock: -1

  angular-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medmatch-ui
    ports:
      - "8080:80"
    depends_on:
      - iris-backend
